export const baseUrl = 'https://bookzone143.herokuapp.com'

//Get BookNEW
export const PRODUCT_BOOK_NEW_REQUEST = 'PRODUCT_BOOK_NEW_REQUEST'
export const PRODUCT_BOOK_NEW_SUCCESS = 'PRODUCT_BOOK_NEW_SUCCESS'
export const PRODUCT_BOOK_NEW_FAIL = 'PRODUCT_BOOK_NEW_FAIL'


//Get BookFree
export const BOOK_FREE_REQUEST = 'BOOK_FREE_REQUEST'
export const BOOK_FREE_SUCCESS = 'BOOK_FREE_SUCCESS'
export const BOOK_FREE_FAIL = 'BOOK_FREE_FAIL'

//Get BookSHOP
export const BOOK_SHOP_REQUEST = 'BOOK_SHOP_REQUEST'
export const BOOK_SHOP_SUCCESS = 'BOOK_SHOP_SUCCESS'
export const BOOK_SHOP_FAIL = 'BOOK_SHOP_FAIL'

//Get BookPOPULAR
export const PRODUCT_BOOK_POPULAR_REQUEST = 'PRODUCT_BOOK_POPULAR_REQUEST'
export const PRODUCT_BOOK_POPULAR_SUCCESS = 'PRODUCT_BOOK_POPULAR_SUCCESS'
export const PRODUCT_BOOK_POPULAR_FAIL = 'PRODUCT_BOOK_POPULAR_FAIL'

//Get BookBest
export const PRODUCT_BOOK_BEST_REQUEST = 'PRODUCT_BOOK_BEST_REQUEST'
export const PRODUCT_BOOK_BEST_SUCCESS = 'PRODUCT_BOOK_BEST_SUCCESS'
export const PRODUCT_BOOK_BEST_FAIL = 'PRODUCT_BOOK_BEST_FAIL'

//Get BookDetail
export const PRODUCT_BOOK_DETAIL_REQUEST = 'PRODUCT_BOOK_DETAIL_REQUEST'
export const PRODUCT_BOOK_DETAIL_SUCCESS = 'PRODUCT_BOOK_DETAIL_SUCCESS'
export const PRODUCT_BOOK_DETAIL_FAIL = 'PRODUCT_BOOK_DETAIL_FAIL'

//Get BookDetail
export const BOOK_DETAIL_FREE_REQUEST = 'BOOK_DETAIL_FREE_REQUEST'
export const BOOK_DETAIL_FREE_SUCCESS = 'BOOK_DETAIL_FREE_SUCCESS'
export const BOOK_DETAIL_FREE_FAIL = 'BOOK_DETAIL_FREE_FAIL'

//Get ContactUs CONTACT
export const CONTACT_US_REQUEST = 'CONTACT_US_REQUEST'
export const CONTACT_US_SUCCESS = 'CONTACT_US_SUCCESS'
export const CONTACT_US_FAIL = 'CONTACT_US_FAIL'


//Get Faqs FAQs
export const FAQs_US_REQUEST = 'FAQs_US_REQUEST'
export const FAQs_US_SUCCESS = 'FAQs_US_SUCCESS'
export const FAQs_US_FAIL = 'FAQs_US_FAIL'

//Get BookCategory CATEGORY
export const BOOK_CATEGORY_REQUEST = 'BOOK_CATEGORY_REQUEST'
export const BOOK_CATEGORY_SUCCESS = 'BOOK_CATEGORY_SUCCESS'
export const BOOK_CATEGORY_FAIL = 'BOOK_CATEGORY_FAIL'

//Get BookCategory Detail
export const DETAIL_CATEGORY_REQUEST = 'DETAIL_CATEGORY_REQUEST'
export const DETAIL_CATEGORY_SUCCESS = 'DETAIL_CATEGORY_SUCCESS'
export const DETAIL_CATEGORY_FAIL = 'DETAIL_CATEGORY_FAIL'


//Get BookShopDetail
export const BOOK_SHOP_DETAIL_REQUEST = 'BOOK_SHOP_DETAIL_REQUEST'
export const BOOK_SHOP_DETAIL_SUCCESS = 'BOOK_SHOP_DETAIL_SUCCESS'
export const BOOK_SHOP_DETAIL_FAIL = 'BOOK_SHOP_DETAIL_FAIL'

//profile
export const PROFILE_REQUEST = 'PROFILE_REQUEST'
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export const PROFILE_FAIL = 'PROFILE_FAIL'